### ISSUE TITLE
associatedFieldName is missing on facet object

### ISSUE THREAD

**Issue by mwinkelm** [FACT-Finder-Web-Components/ff-web-components#34]
Hi,

I'm currently facing the challenge to detect whether a particular filter is activated or not.
In the facets array of the search result there are objects that only contain the localized name of the filter, which might differ from channel to channel. The corresponding ID is missing. It is just present in the objects of the `element` field as the field `associatedFieldName`. I assume it is no good idea to use this for such a detection.

![ff-associatedFieldname](https://user-images.githubusercontent.com/6881829/83871035-98f95500-a72f-11ea-84b0-7c7032f6b7d7.png)

Any thoughts on how to achieve that?

Thanks,
Markus

**Comment by mwinkelm** [comment]
Additionally I have the requirement to hide this one particular filter in the `<ff-asn>` element. How to achieve this? I tried empty templates for this filter without luck:
```html
<ff-asn-group for-group="Category">
    <div data-container="detailedLinks"></div>
    <div data-container="hiddenLinks"></div>
    <div data-container="showLess"></div>
    <div data-container="showMore"></div>
    <div slot="filterSearch"></div>
    <div slot="groupCaption"></div>
  </ff-asn-group>
```

**Comment by omikron-fp** [comment]
Hi @mwinkelm.
at what point do you need to know whether the filter is activated? I think I need a bit more context to fully understand the problem.
Do you access the response as it is reported by the browser? Like in your screenshot? Or do you use the transformed response as provided by WebComponents?
In case you access the unmodified response, the facet elements contain a property `selected`. Furthermore, the `filters` collection contains all currently active filters.
Does this go into the direction of your problem?
![image](https://user-images.githubusercontent.com/42067426/84026213-343b3600-a98d-11ea-9023-ca4bc9c37e95.png)

**Comment by omikron-fp** [comment]
Regarding the hiding of a particular filter. From the snippet you posted it looks like you want to hide the entire **Category** group. Is this correct? Or would you like to only hide a single group element. For example hide "Climbing" but not "Equipment"?

In case you want to hide the entire group, you have two options.
1) CSS - because there are default styles active, you need `!important`. For example:
    ```css
    [for-group="Category"] {
      display: none !important;
    }
    ```
2) JavaScript
    You can remove the filter data entirely from the response by subscribing to the `asn` event using `addCallback()` and filtering out the unwanted group. Note that it has to be in-place!
    ```html
    <script>
    document.addEventListener(`ffReady`, ({ resultDispatcher }) => {
        resultDispatcher.addCallback(`asn`, groups => {
            const filteredGroups = groups.filter(g => g.name !== `Category`);
            groups.splice(0, Infinity, ...filteredGroups);
        });
    });
    </script>
    ````

Not sure if this is what you are looking for though.

**Comment by mwinkelm** [comment]
@omikron-fp I'm talking about the response reported by the browser. And I'm refering to the facets field. I'm interested in identifying an entry in this array in a predictable way. Just have a look at the first level of fields:

```
facets: [
  {
    detailedLinks: 5
    elements: [,…]
    filterStyle: "TREE"
    name: "Category"
    selectedElements: []
    selectionType: "singleHideUnselected"
    showPreviewImages: false
    type: "CATEGORY_PATH"
    unit: ""
  } 
  ...
]
```
Currently we are using the field `name` to identify if a particular filter is included in the array (so we can assume it is activated in FF backoffice). BUT this field may have different values in different channels because it is no ID, but a localized field. There is nothing like an ID we could use for that purpose. But maybe this is the completely wrong approach.

**Comment by mwinkelm** [comment]
> Not sure if this is what you are looking for though.

You got that right. I like the CSS solution and it's my bad that I didn't realized this possibility. Thank you!

But the CSS solution has the same problem as explained above, correct? Because in another channel this might be translated somehow else and then the selector doesn't match any more.

**Comment by mwinkelm** [comment]
In general, this comparison `g.name !== 'Category'` is problematic, because you can't assume that `name` always has the value "Category".

Maybe for now we could "solve" this with a convention that those localisations must be the same in all channels for the filter we want to hide?

**Comment by omikron-fp** [comment]
The `associatedFieldName` should be safe to use as an ID replacement. You can use it to identify a group independent from localisation.
While a convention to use the same group name across all channels should work, you would lose localised display names which is probably not what you want.

In the context of WebComponents, in particular the `<ff-asn-group for-group="Manufacturer">`, it is possible to reference the `associatedFieldName`. This should make the implementation localisation-agnostic.
As WebComponents' `for-group` attribute compares against the `name` field, we have to overwrite it with the value of `associatedFieldName`. To preserve the localised display name, we can add a new property to the group object.
```js
document.addEventListener(`ffReady`, ({ resultDispatcher }) => {
    resultDispatcher.addCallback(`asn`, groups => {
        const assocName = `Manufacturer`;
        const manufacturerGroups = groups.filter(g => g.elements.some(e => e.associatedFieldName === assocName));
        manufacturerGroups.forEach(g => {
            g.displayName = g.name;
            g.name = assocName;
        });
    });
});
```
The affected parts of the ASN template would look like this:
```html
<ff-asn>
  <ff-asn-group for-group="Manufacturer">  <!-- now referencing the associatedFieldName -->
    <div slot="groupCaption">
      {{group.displayName}}
    </div>
  </ff-asn-group>
</ff-asn>
```

I hope this works for you.

**Comment by mwinkelm** [comment]
Thanks for this quick and deep support, @omikron-fp. I will give this a try as it fits our needs.

**Comment by mwinkelm** [comment]
Hi @omikron-fp,

your solution works somehow. I didn't limited the change to one of the filters but do it for every filter, like so (TypeScript):

```javascript
return this.resultDispatchWrapper('asn', (groups: Array<FactFinderAsnGroup>) => {
  groups.map((group) => {
	group.displayName = group.name;
	if (group.elements[0]?.associatedFieldName) {
	  group.name = group.elements[0]?.associatedFieldName;
	} else if (group.selectedElements[0]?.associatedFieldName) {
	  group.name = group.selectedElements[0].associatedFieldName;
	} else {
	  group.name = undefined;
	}
  });
});
```
I discovered that when the filter is selected the elements array is empty and the identifier is only available in the selectedElements array.

Unfortunately now I get an error in the console:
`could not invoke subscribe function  [object Object] : TypeError: Cannot add property displayName, object is not extensible` which is related to `bundle.js`.

Is it even allowed to add displayName to the object?

**Comment by omikron-fp** [comment]
Hi @mwinkelm,

Indeed, the `elements` array may be empty. I didn't include this in my example. But at least one of `elements` and `selectedElements`  has items. If both are empty, the entire group doesn't appear in the result.
For simplicity you could get the first element of their concatenation.
```js
group.elements.concat(group.selectedElements)[0].associatedFieldName
```
According to the API specification, `associatedFieldName` is always present and never empty for facet elements. Have you observed this differently?

I don't recommend setting `group.name = undefined`. Although that `else` case in your example should never occur, if it actually does, and does so multiple times, WebComponents will no longer be able to tell the groups apart.

Regarding the `Cannot add property displayName, object is not extensible` error. I can't reproduce it and I am not aware of us freezing response data.
Does the error occur as soon as you assign `displayName` in your example?
Is there a possibility the objects get frozen somewhere before being provided by `resultDispatchWrapper`?

**Comment by omikron-fp** [comment]
Hi @mwinkelm,
Any news on this topic?

**Comment by mwinkelm** [comment]
Hi @omikron-fp, I still have to have a deeper look into this. But I only have to get rid of the error I mentioned. I guess it's something in our code.

**Comment by mwinkelm** [comment]
So, @omikron-fp, I looked again at our code. For reference, this is how `resultDispatchWrapper` looks like:
```javascript
private async resultDispatchWrapper(topic: FactFinderResultTopics, callback: (result: any) => void) {
    const factfinder = await this.factfinder;
    return factfinder.communication.ResultDispatcher.subscribe(
      topic,
      (resultData: Array<Array<FactFinderAsnGroupElement>>) => {
        // process the result and or the event
        this.zone.run(() => callback(resultData));
      },
    );
  }
```
I don't see that the result of ResultDispatcher gets freezed anywhere.

When I comment out the line where `displayName` gets assigned the error is gone. So no other code snippet is involved.

**Comment by mwinkelm** [comment]
And when using `forEach` instead of `map` (and not even assigning something to `displayName`), like

```javascript
groups.forEach((group) => {
        // group.displayName = group.name;
        if (group.elements[0]?.associatedFieldName) {
          group.name = group.elements[0]?.associatedFieldName;
        } else if (group.selectedElements[0]?.associatedFieldName) {
          group.name = group.selectedElements[0].associatedFieldName;
        }
      });
```
I get the following error:
`could not invoke subscribe function  [object Object] : TypeError: Cannot assign to read only property 'name' of object '[object Object]'`

**Comment by mwinkelm** [comment]
Related to this problem I now have the situation that I can not use `blacklist` attribute of `ff-filter-cloud`, because the `associatedFieldName` and `name` of the `selectedFilters` within the `asn` object is not deterministic. See this:

![ff-filterCloud](https://user-images.githubusercontent.com/6881829/85625364-a2f5e000-b66b-11ea-8d44-ed228a5ba802.png)

As the filter cloud does not use the values from `filters` field in `result` object, but the `selectedFilters` field in `asn` object, this problem exists.

**Comment by a-laurowski** [comment]
Hi @mwinkelm  

**Regarding the immutable objects:**
Unfortunately we were not able to reproduce the error on our Angular demo. Manipulating the `asnGroups` in `ResultDispatcher.addCallback` didn't throw an error.
Would you mind using this demo to check if the your logic works there? 
Its available in our demos repository: https://github.com/FACT-Finder-Web-Components/demos/tree/release/3.x/custom-components/angular-carousel

There are also other possible issues, which we want to clarify:
* Do you use any kind of state manager in Angular, like NgRx? Direct modifying object already stored in state might throw similar error, as the one you mentioned.

* According to snippet, you pasted https://github.com/FACT-Finder-Web-Components/ff-web-components/issues/34#issuecomment-648243882 - didn't any used library override the native` forEach`, making the iterated object being only for read?


**Regarding "associatedFieldName values" bug:**
Thanks for reporting that! We already solved it.
The next release of the Web Components will have proper fix included.

**Comment by omikron-fp** [comment]
Hi @mwinkelm, is this issue still ongoing? Is there anything we can assist with?

**Comment by omikron-fp** [comment]
Assuming issue is resolved.

**Comment by mwinkelm** [comment]
@omikron-fp Issue is not resolved yet on our side, but needs further investigation before from us.

@a-laurowski We use NGXS as a state management. At this place in the code the object is not stored in the state yet. I'm not aware of any library overriding forEach in our case, but thanks for this hint. We will investigate this at a later point in time.

**Comment by omikron-fp** [comment]
@mwinkelm Thanks for the update. Keep us posted so we can assist if necessary.

**Comment by omikron-fp** [comment]
FYI @mwinkelm,
#35 was added to the [4.0 Milestone](https://github.com/FACT-Finder-Web-Components/ff-web-components/milestone/1) which is going to see a release candidate around mid-September.
It will make the workaround mentioned here redundant.

**Comment by omikron-fp** [comment]
Remaining issue was solved according to @mwinkelm.
